Creating db
SergioJaramilloL/alamesa-server pull request #1
Opened 2020-11-18 01:26 UTC by SergioJaramilloL

Creating data base and first entity (client) agregate methods list, show, create, destroy

Create by: all members

2020-11-18 11:39 UTC, simonhoyos requested changes

2020-11-18 11:39 UTC, simonhoyos commented on package.json
> +    "nodemon": "^2.0.6"
Nodemon no es necesario que sea una dependencia de producción. Puede ser una dependencia de desarrollo

2020-11-18 11:39 UTC, simonhoyos commented on src/controllers/client.controller.js
> +  listar( req, res ) {
cambiar el nombre a Inglés

2020-11-18 11:39 UTC, simonhoyos commented on src/models/client.model.js
> +  name: 'String',
el valor es String sin las comillas

2020-11-18 11:39 UTC, simonhoyos commented on yarn-error.log
> +Arguments:
este archivo lo puedes borrar y luego agregarlo a .gitignore

2020-11-20 15:40 UTC, simonhoyos approved these changes

2020-11-20 15:56 UTC, andress20 approved these changes

2020-11-20 16:00 UTC, carosalazar28 approved these changes

2020-11-20 16:01 UTC, danielsespitia approved these changes

2020-11-20 21:36 UTC, merged