Feature-BCK001
SergioJaramilloL/alamesa-server pull request #12
Opened 2020-11-28 19:35 UTC by danielsespitia

Updated Client and Restaurant Models with new required profile data.

2020-11-28 19:50 UTC, andress20 requested changes

2020-11-28 19:50 UTC, andress20 commented on src/controllers/restaurant.controllers.js
>        const token = jwt.sign(
Veo que quitaste `nit` y `deposit` (por no ser requeridos por el modelo supongo), podriamos entonces tambien quitar `nit` y `deposit` del destructuring que hacemos a` req.body` por mi parte no los estamos usando para nada.

2020-11-28 19:50 UTC, andress20 commented on src/models/client.model.js
> +  },
phone Boolean?

2020-11-28 20:06 UTC, carosalazar28 commented on src/controllers/restaurant.controllers.js
>        const token = jwt.sign(
Ese nit y deposit deberian estar en el perfil del restaurante porque si son requeridos para acciones de reserva

2020-11-28 20:42 UTC, danielsespitia commented on src/controllers/restaurant.controllers.js
>        const token = jwt.sign(
Andrés tiene razón, en el modelo de Sign Up no son requeridos pero como dice Caro, deben ser requeridos en el perfil de Restaurante como tal (ya que no se necesita el NIT ni el deposit para crear la cuenta sino que se pueden validar esos datos después al ingresar al perfil)

2020-11-29 14:36 UTC, simonhoyos requested changes

2020-11-29 14:36 UTC, simonhoyos commented on src/controllers/restaurant.controllers.js
> +      const restaurant = await Restaurant.create({ name, email, password, terms })
Falta encriptar la contraseña

2020-11-29 15:58 UTC, SergioJaramilloL approved these changes, later dismissed

2020-11-29 19:12 UTC, carosalazar28 commented on src/controllers/restaurant.controllers.js
> +      const restaurant = await Restaurant.create({ name, email, password, terms })
La encriptación de la constraseña ya se aprobó en el anterior pullrequest, nos recomiendas colocarla acá tambien? o cuando hagamos merge resolvemos que quede con los cambios de lo que esta en develop?

2020-11-29 23:34 UTC, simonhoyos commented on src/controllers/restaurant.controllers.js
> +      const restaurant = await Restaurant.create({ name, email, password, terms })
cuando hagan merge y resuelvan los conflictos

2020-11-29 23:34 UTC, simonhoyos approved these changes, later dismissed

2020-11-30 00:10 UTC, andress20 approved these changes, later dismissed
En el Merge recodar dejar en el restaurant controller la parte que tiene el password encriptado.

2020-11-30 00:10 UTC, andress20 commented on src/controllers/restaurant.controllers.js
>        const token = jwt.sign(
Pero entonces deben ir en otro metodo diferente a `signUp` ... porque del formulario `signUp` nunca vamos a recibir esta data. Posiblemente en el metodo `Update`?

2020-11-30 00:10 UTC, andress20 commented on src/controllers/restaurant.controllers.js
> +      const restaurant = await Restaurant.create({ name, email, password, terms })
> Falta encriptar la contraseña

Simon, la encriptacion se encuentra desarrollada en el otro PR (log002), así que creo que lo importante es tener mucho cuidado cuando hagamos merge que al arreglar el conflicto que va a surgir, dejar la parte que ya tiene la encriptacion.

2020-11-30 14:40 UTC, SergioJaramilloL approved these changes

2020-11-30 14:52 UTC, andress20 approved these changes

2020-11-30 14:55 UTC, carosalazar28 approved these changes

2020-11-30 14:57 UTC, merged