Feature bck004
SergioJaramilloL/alamesa-server pull request #29
Opened 2020-12-10 23:24 UTC by danielsespitia

Added Reservation Model/View/Controller with their respective references to Client and Restaurant

2020-12-11 00:52 UTC, SergioJaramilloL submitted a review, later dismissed

2020-12-11 11:16 UTC, simonhoyos requested changes

2020-12-11 11:16 UTC, simonhoyos commented on src/controllers/reservation.controller.js
> +      const { clientId } = req.params;
El client id ya debe llegar a este controlador a través del middleware de autenticación. No es necesario pasarlo por los parámetros de ruta

2020-12-11 11:16 UTC, simonhoyos commented on src/controllers/reservation.controller.js
> +    res.status(200).json(reservationRestaurant)
Este método se podría llamar mejor showReservation ya que la idea es mostrar una reserva y no un restaurante. Además es bueno envolver el código en un try catch para manejar los errores

2020-12-11 11:16 UTC, simonhoyos commented on src/controllers/reservation.controller.js
> +  async showClient(req, res) {
Con el mismo método anterior puedes mostrar el restaurante y el cliente. No se si sea necesario tener dos controladores diferentes (esto depende de su caso de uso). Adicionalmente este código también lo puedes envolver en un try catch

2020-12-11 20:14 UTC, carosalazar28 requested changes

2020-12-11 20:14 UTC, carosalazar28 commented on src/controllers/reservation.controller.js
> +      const { clientId } = req.params;
Sería borrar estás dos líneas

2020-12-11 20:14 UTC, carosalazar28 commented on src/controllers/reservation.controller.js
> +  async showClient(req, res) {
De pronto si es necesario tener dos métodos diferentes ya que el restaurante necesita traer la información de la reserva diferente que el cliente.

2020-12-11 20:14 UTC, carosalazar28 commented on src/controllers/reservation.controller.js
> +  async update( req, res ) {
Una vez enviada la reserva el cliente puede modificarla?
No se que piensen los demás sobre esté método pero yo diría que no permitir el cambio de información una vez enviada la reserva.

2020-12-11 20:35 UTC, simonhoyos commented on src/controllers/reservation.controller.js
> +      const { clientId } = req.params;
No solo la del clientId, el id del restaurante si llegaría por los parámetros de la url porque el restaurante no está autenticado

2020-12-11 20:36 UTC, simonhoyos commented on src/controllers/reservation.controller.js
> +  async showClient(req, res) {
Valido

2020-12-14 19:22 UTC, simonhoyos approved these changes

2020-12-14 20:59 UTC, carosalazar28 approved these changes

2020-12-14 21:02 UTC, SergioJaramilloL approved these changes

2020-12-14 21:16 UTC, merged